services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.160.0
    restart: unless-stopped
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - grafana-lgtm
      - aspire-dashboard
  grafana-lgtm:
    image: grafana/otel-lgtm:0.33.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/otel-lgtm/grafana/conf/provisioning/dashboards/custom/github-copilot.json
    volumes:
      - ./github-copilot.json:/otel-lgtm/grafana/conf/provisioning/dashboards/custom/github-copilot.json:ro
      - ./dashboards-provisioning.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/custom.yaml:ro
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:13.5.2
    ports:
      - "18888:18888"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true