version: "3.9"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 