name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnetCoreProjects: ["ApplicationDiagnosticsNetCore", "CakeBuild/ConsoleAppSample", "CSharp7", "CSharp8", "DemoCode.Utils", "DebuggingScenarios", "PulumiDemo", "DarkSideOfCSharp", "MakingDotNETApplicationsFaster"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Install dependencies
      run: dotnet restore ${{ matrix.dotnetCoreProjects }}
    - name: Build
      run: dotnet build ${{ matrix.dotnetCoreProjects }} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{ matrix.dotnetCoreProjects }} --no-restore --verbosity normal
