name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        dotnetCoreProjects: ["DemoCode.Utils", "WorkWithTelemetryInDotNET"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.x
          7.x
          8.x
    - name: Initialize CodeQL
      if: matrix.operating-system == 'ubuntu-latest' 
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'
    - name: Install dependencies
      run: dotnet restore ${{ matrix.dotnetCoreProjects }}
    - name: Build
      run: dotnet build ${{ matrix.dotnetCoreProjects }} /p:UseSharedCompilation=false --configuration Release --no-restore
    - name: Perform CodeQL Analysis
      if: matrix.operating-system == 'ubuntu-latest'
      uses: github/codeql-action/analyze@v2
    - name: Test
      run: dotnet test ${{ matrix.dotnetCoreProjects }} --no-restore --verbosity normal
